spring:
  application:
    name: OnlineFoodStorage
  datasource:
    url: jdbc:postgresql://localhost:5432/OnlineFoodStorage
    password: 1
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
      caches:
        users: 50
        categories: 50
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: DFANWEGOINEFOINAROIGNESOIGOERWISEGOIEOISNGFOSIEGOZNESOIGFZSOINGZOS
  token:
    validity: 604800

server:
  port: 8080
